### ISSUE TITLE
Integration not working after HA update to 2022.8.0b4

### ISSUE THREAD

**Issue by zuppl** [marcelwestrahome/home-assistant-niu-component#36]
After upgrading to 2022.8.0b4 no values are returned.

**Comment by syssi** [comment]
Do you see any errors at the Home Assistant log?

**Comment by zuppl** [comment]
Logger: homeassistant.components.sensor
Source: custom_components/niu/sensor.py:436 
Integration: Sensor (documentation, issues) 
First occurred: 14:10:28 (1 occurrences) 
Last logged: 14:10:28

Error while setting up niu platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/niu/sensor.py", line 392, in setup_platform
    NiuSensor(
  File "/config/custom_components/niu/sensor.py", line 503, in __init__
    self._state = self._data_bridge.dataTrack(self._id_name)
  File "/config/custom_components/niu/sensor.py", line 436, in dataTrack
    (self._dataTrackInfo["data"][0][id_field]) / 1000
TypeError: 'bool' object is not subscriptable

**Comment by syssi** [comment]
Let's discuss the issue here: #37 

Duplicate: ##37
