### ISSUE TITLE
KeyError: 'distance'

### ISSUE THREAD

**Issue by zimjjan** [marcelwestrahome/home-assistant-niu-component#43]
I configured the integration as to the README but unfortunately I get the following error
```
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/niu/sensor.py", line 392, in setup_platform
    NiuSensor(
  File "/config/custom_components/niu/sensor.py", line 499, in __init__
    self._state = self._data_bridge.dataDist(self._id_name)
  File "/config/custom_components/niu/sensor.py", line 425, in dataDist
    return self._dataMoto["data"]["lastTrack"][id_field]
KeyError: 'distance'
```

Configuration in configuration.yml
```
- platform: niu
    username: *****
    password: *****
    country: 49
    scooter_id: 0
    monitored_variables:
      - BatteryCharge          # Battery
      - Isconnected            # Battery
      - TimesCharged           # Battery
      - temperatureDesc        # Battery
      - Temperature            # Battery
      - BatteryGrade           # Battery
      - CurrentSpeed           # Moto
      - ScooterConnected       # Moto (has attributes lon. lat. for plotting on a map)
      - IsCharging             # Moto
      - IsLocked               # Moto
      - TimeLeft               # Moto
      - EstimatedMileage       # Moto
      - centreCtrlBatt         # Moto
      - HDOP                   # Moto
      - Longitude              # Moto
      - Latitude               # Moto
      - totalMileage           # OverAll
      - DaysInUse              # OverAll
      - Distance               # Distance
      - RidingTime             # Distance
      - LastTrackStartTime     # LastTrack
      - LastTrackEndTime       # LastTrack
      - LastTrackDistance      # LastTrack
      - LastTrackAverageSpeed  # LastTrack
      - LastTrackRidingtime    # LastTrack
      - LastTrackThumb         # LastTrack
 ```

NIU NQi Sport FW TRA01E19

**Comment by marcelwestrahome** [comment]
just for testing remove distance see what happen then

**Comment by zimjjan** [comment]
```
2022-09-03 16:42:03.947 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_batterycharge
2022-09-03 16:42:03.948 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_isconnected
2022-09-03 16:42:03.949 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_timescharged
2022-09-03 16:42:03.951 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_temperaturedesc
2022-09-03 16:42:03.956 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_temperature
2022-09-03 16:42:03.957 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_batterygrade
2022-09-03 16:42:03.958 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_currentspeed
2022-09-03 16:42:03.960 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_scooterconnected
2022-09-03 16:42:03.961 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_ischarging
2022-09-03 16:42:03.964 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_islocked
2022-09-03 16:42:03.966 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_timeleft
2022-09-03 16:42:03.967 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_estimatedmileage
2022-09-03 16:42:03.968 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_centrectrlbatt
2022-09-03 16:42:03.969 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_hdop
2022-09-03 16:42:03.970 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_longitude
2022-09-03 16:42:03.971 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_latitude
2022-09-03 16:42:03.973 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_totalmileage
2022-09-03 16:42:03.974 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_daysinuse
2022-09-03 16:42:03.975 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_ridingtime
2022-09-03 16:42:03.976 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_lasttrackstarttime
2022-09-03 16:42:03.978 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_lasttrackendtime
2022-09-03 16:42:03.979 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_lasttrackdistance
2022-09-03 16:42:03.980 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_lasttrackaveragespeed
2022-09-03 16:42:03.981 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_lasttrackridingtime
2022-09-03 16:42:03.983 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.niu entity: sensor.niu_scooter_epache_207_lasttrackthumb
```

**Comment by vincentnk** [comment]
Same issue here after newly installing the component.
I commented out the - Distance, and receive now the KeyError 'ridingTime'. 

Edit: also removed the RidingTime from configuration, now have the following error in logs:

Logger: homeassistant.components.sensor
Source: custom_components/niu/sensor.py:436
Integration: Sensor (documentation, issues)
First occurred: 6:18:35 PM (1 occurrences)
Last logged: 6:18:35 PM

```
Error while setting up niu platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/niu/sensor.py", line 392, in setup_platform
    NiuSensor(
  File "/config/custom_components/niu/sensor.py", line 503, in __init__
    self._state = self._data_bridge.dataTrack(self._id_name)
  File "/config/custom_components/niu/sensor.py", line 436, in dataTrack
    (self._dataTrackInfo["data"][0][id_field]) / 1000
KeyError: 0
```
 

Please let me know if I can help debug, appreciate the work you put in for this custom component!

**Comment by marcelwestrahome** [comment]
are you all using the last version of HA ?. To track the issue, please can you try only with the battery sensors. May be there is an update for certain scooters, but I do not having any issues with two niu scooters

**Comment by vincentnk** [comment]
Since new 2.0 update this has been resolved for me. 

Very nice integration @marcelwestrahome, thanks for your hard work!

**Comment by marcelwestrahome** [comment]
component has a new setup
